services:
  app:
    build: .
    container_name: expense-tracker
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/expenseTracker
      - JWT_SECRET=expense_tracker_key
      - NODE_ENV=development
      - PORT=2000
    ports:
      - "2000:2000"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:13-alpine
    container_name: expenseTracker-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expenseTracker
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
